AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    # self === the serverless.yml file
    # provider.stage will bring the current stage
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    # defining the attribute
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S #string
      - AttributeName: status
        AttributeType: S
      - AttributeName: endingAt
        AttributeType: S
    # attaching it with db
    KeySchema:
      - AttributeName: id
        KeyType: HASH # means keep it unique
    GlobalSecondaryIndexes:
      - IndexName: statusAndEndDate
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: endingAt
            KeyType: RANGE
        # this tells DB to create keep copies of this indexes
        # in the virtual table that it creates for indexing
        Projection:
          ProjectionType: ALL
