AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    # self === the serverless.yml file
    # provider.stage will bring the current stage
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    # defining the attribute
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S #string
    # attaching it with db
    KeySchema:
      - AttributeName: id
        KeyType: HASH # this means make it as a partition key/primary key
